---
abstract: 'Ensure a Changes file looks exactly like it would if it was machine generated.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0.96'
  Text::Wrap: '0'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-CPAN-Changes-ReallyStrict
provides:
  Test::CPAN::Changes::ReallyStrict:
    file: lib/Test/CPAN/Changes/ReallyStrict.pm
    version: '1.000004'
  Test::CPAN::Changes::ReallyStrict::Object:
    file: lib/Test/CPAN/Changes/ReallyStrict/Object.pm
    version: '1.000004'
requires:
  CPAN::Changes: '0.27'
  Class::Tiny: '0'
  Encode: '0'
  Test::Builder: '0'
  Try::Tiny: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Test-CPAN-Changes-ReallyStrict/issues
  homepage: https://github.com/kentnl/Test-CPAN-Changes-ReallyStrict
  repository: https://github.com/kentnl/Test-CPAN-Changes-ReallyStrict.git
version: '1.000004'
